### ISSUE TITLE
Does this work with `wrangler preview`?

### ISSUE THREAD

**Issue by lfender6445** [cloudflare/workers-graphql-server#17]
![image](https://user-images.githubusercontent.com/959505/68962121-df8e5e80-07a1-11ea-8c1c-44b23eb22143.png)
![image](https://user-images.githubusercontent.com/959505/68962124-e0bf8b80-07a1-11ea-96bf-357e81652592.png)

I can successfully preview the project, but hitting a wall when trying to contact the apollo server - the error that comes back seems to indicate a problem intrinsic to cloudflare worker previews?

**Comment by lfender6445** [comment]
ive just discovered this works just fine with `wrangler publish` but am still not entirely certain why

**Comment by signalnerve** [comment]
@lfender6445 – great question! i haven't tested it with `wrangler preview` since we changed some of how the preview service works. my guess is that because the preview URLs are dynamic, the graphiql preview might have some issues connecting to it. that being said, if it was making relative URL requests (`/graphql` vs `https://abcdef.cloudflareworkers.com/graphql), maybe that would be the fix. will look into this, thank you for filing an issue!

**Comment by lfender6445** [comment]
thanks kristain! love your youtube videos by the way, i wish all programming tutorials were done in the same format
